List<String> gebzeIlceleri = [
    'Barbaros',
    'Çayırova',
    'Darıca',
    'Eskihisar',
    'Fatih',
    'Gebze Merkez',
    'Güzeller',
    'İstasyon',
    'Kızılay',
    'Mimar Sinan',
    'Muallimköy',
    'Osman Yılmaz',
    'Ovacık',
    'Pelitli',
    'Sultan Orhan',
    'Tatlıkuyu',
    'Tavşancık',
    'Yavuz Sultan Selim',
  ];